### ISSUE TITLE
How to cite this software?

### ISSUE THREAD

**Issue by BiodeB** [santiago1234/codonr#1]
Dear Sir,

CodonR is a tremendous software for the calculation of tAI, and I used it in my work. However, I want to know is there any publication related to this software available. How can I cite this software, kindly let me know.

Thanks,
Debajyoti

**Comment by santiago1234** [comment]
Dear BiodeB,

I am glad you find it useful, you can cite the following paper: https://genomebiology.biomedcentral.com/articles/10.1186/s13059-020-02251-5
